### ISSUE TITLE
Upload failure with "speed up" patch

### ISSUE THREAD

**Issue by 0xFACE** [0xFACE/BlueBasic-loader#14]
BLE device (HM-11) crashing with second data chunk.

Seems device doesn't like merged lines.
This requires further investigation.

**Comment by 0x2b3bfa0** [comment]
There are three options:
1. I fix the code to upload by lines.
2. You revert that commit.
3. We find/fix the problem.

:smiling_imp: 

I would prefer to choose 1 or 3, but that's up to you.
