### ISSUE TITLE
Add a progress bar to upload process

### ISSUE THREAD

**Issue by 0x2b3bfa0** [0xFACE/BlueBasic-loader#3]
Wouldn't be a good idea to add a progress bar to the upload process?

I don't have a BLE capable computer, however if you record for me a asciinema of the uploading process, I could make a progress bar for it.

**Comment by 0xFACE** [comment]
Sure. 
I'm not familiar with asciinema, but if it will works with raspberry pi I will record session for you.
Thanks.

**Comment by 0x2b3bfa0** [comment]
On Raspbian it _should_ be easy:

```
sudo apt-get install asciinema
asciinema rec
bash load 00:FA:CE:00:FA:CE script.bas
exit
```

Please refer to: https://asciinema.org/docs/installation

**Comment by 0xFACE** [comment]
Now it looks like this:

https://asciinema.org/a/7iodzrpy8iqmxno4u11d25kkv

**Comment by crushedice2000** [comment]
I'm busy now, however I'll do it in a few hours.

**Comment by crushedice2000** [comment]
@0xFACE: Also, would be great you add the "enhacement" label to this issue.

**Comment by crushedice2000** [comment]
@0xFACE: Feel free to check to PR. ![https://assets-cdn.github.com/images/icons/emoji/unicode/1f608.png](https://assets-cdn.github.com/images/icons/emoji/unicode/1f608.png)

**Comment by crushedice2000** [comment]
Also I would improve a bit the program if you could provide me the gatttool success exit status. You can discover it running a success `gatttool` command and then running `echo $?`

**Comment by 0xFACE** [comment]
Progress bar looks good : https://asciinema.org/a/2vpjc7ecipmipyfrjkmlonod7

`gatttool` success exit code is 0, on connect error the exit code is 1

Good idea, we need break file reading loop when `gatttool` exits with exitcode !=0.

**Comment by crushedice2000** [comment]
@0xFACE: Try the new PR :smile:

**Comment by crushedice2000** [comment]
Could you record an asciinema of a wrong/success upload with the latest PR?

**Comment by crushedice2000** [comment]
@0xFACE: Did you check the latest PR?

**Comment by 0xFACE** [comment]
https://asciinema.org/a/96izijxkb6vpqcim5wuaymuty
As you can see, gatttool exits with 0 code for this error: 
`Characteristic Write Request failed: Too many prepare writes have been queued`

**Comment by 0x2b3bfa0** [comment]
Now I'll travel. Tomorrow I'll review the code and fix a few issues I've observed. Thanks for your patience.

Helio

**Comment by 0xFACE** [comment]
Ok, thank you very much for your help ;-)

**Comment by crushedice2000** [comment]
@0xFACE: Please test now the error handling system ;-)

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Does all work well now?

**Comment by 0xFACE** [comment]
Yes. I just successfully uploaded script  with long line ;-)

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Now I'll travel. Later I'll enhace the progress bar to increment even with each line chunk, and then I'll close this issue with another PR. Also, please consider to test the error handling system.

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Please test the new PR. It should be better. Also it improves the upload speed in short lines.
