### ISSUE TITLE
Can't write program line

### ISSUE THREAD

**Issue by 0xFACE** [0xFACE/BlueBasic-loader#6]
`100 ADVERT CUSTOM "FF 4C 00 02 15" "74 27 8B DA B6 44 45 20 8F 0C 72 0E AF 05 99 35" M "00"`
`3130302041445645525420435553544f4d20224646203443203030203032203135222022373420323720384220444120423620343420343520323020384620304320373220304520414620303520393920333522204d20223030220d`

gatttool exits with error:
Characteristic Write Request failed: Too many prepare writes have been queued

**Comment by 0x2b3bfa0** [comment]
@0xFACE: How? Why? Where?

How to solve? May be a very long string should be splitted in two sends?

**Comment by 0xFACE** [comment]
No idea what `Too many prepare writes have been queued` error mean.
I'll will try to split string into chunks to discover max "packet" size.

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Googling I've seen that is 512bytes, but this limit is not exceeded.

**Comment by 0xFACE** [comment]
String length must be 180 or less. So limit is 90bytes.

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Try the latest PR. :smiling_imp:
