### ISSUE TITLE
Change program name

### ISSUE THREAD

**Issue by 0x2b3bfa0** [0xFACE/BlueBasic-loader#8]
I think that `load` is so generic to be the name of this command line tool and it should be more descriptive. Please consider switching to one of these names (or propose your own):
- `bbload`
- `bbupload`
- `bluebasic-load`
- `bluebasic-upload`
- `bb-load`
- `bb-upload`

**Comment by 0xFACE** [comment]
Sure, I just took "LOAD" from old ZX Spectrum ;-)
I think "bbload" will be ok (for typing and remembering).
