### ISSUE TITLE
Add Makefile for a easy installation

### ISSUE THREAD

**Issue by 0x2b3bfa0** [0xFACE/BlueBasic-loader#9]
What about adding a Makefile to install this script?

**Comment by 0xFACE** [comment]
If you can provide me PR  I'll be happy ;-)

**Comment by crushedice2000** [comment]
@0xFACE: Now I'm busy making a nearly-perfect code chunk mechanism. Later I'll do ;-)

**Comment by 0x2b3bfa0** [comment]
@0xFACE: Please check (and merge if works) the latest PR. This makefile needs improvement.

Also, please tag this issue as enhancement.

Off-topic: Please consider to open a new issue with the chunk failure.
